filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata: ~
- script:
      lang: javascript
      tag: my_filter
      source: >
        function process(event) {
            var pathname = event.Get("log.file.path");
            var splitString = pathname.split('\\').pop().split('/');
            event.Put("haproxy.hostname", splitString[splitString.length-2])
        }

setup.template.settings:
  setup.template.enabled: true
  setup.template.overwrite: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
